CREATE TABLE `dt_plan` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`desc` TEXT NOT NULL,
	`pw` VARCHAR(250) NOT NULL,
	`salt` VARCHAR(250) NOT NULL,
	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;

CREATE TABLE `dt_planskills` (
	`planskillID` INT(11) NOT NULL AUTO_INCREMENT,
	`planID` INT(11) NOT NULL,
	`skillID` INT(11) NOT NULL,
	`startLvl` TINYINT(4) NOT NULL,
	`endLvl` TINYINT(4) NOT NULL,
	PRIMARY KEY (`planskillID`),
	INDEX `planID` (`planID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;